/**
 * Frontmatter validation for OKF bundle Concepts (rules and sources).
 *
 * The bundle is generated by an external pipeline, so validation guards against a
 * broken or partial export landing in docs/bundle/: warn in dev, fail a production
 * build (via handleValidationResult in the data loaders).
 */

import type { ValidationError, ValidationResult } from './utils';

const RULE_REQUIRED_FIELDS = ['code', 'title', 'description', 'standard', 'source', 'category'] as const;
const SOURCE_REQUIRED_FIELDS = ['slug', 'title', 'description', 'standard'] as const;

function buildResult(errors: ValidationError[], warnings: ValidationError[]): ValidationResult {
  return { valid: errors.length === 0, errors, warnings };
}

function checkRequired(fm: Record<string, unknown>, fields: readonly string[], errors: ValidationError[]): void {
  for (const field of fields) {
    const value = fm[field];
    if (value === undefined || value === null || value === '') {
      errors.push({ field, message: 'Required field is missing or empty', severity: 'error' });
    }
  }
}

/**
 * Validates the frontmatter of a rule Concept (bundle/rules/<source>/<rule>.md).
 *
 * @param fm - Parsed frontmatter object
 * @param sourceSlug - Slug of the bundle folder the file lives in
 */
export function validateRuleFrontmatter(fm: Record<string, unknown>, sourceSlug: string): ValidationResult {
  const errors: ValidationError[] = [];
  const warnings: ValidationError[] = [];

  if (fm.type !== 'Validation Rule') {
    errors.push({ field: 'type', message: `Expected type "Validation Rule", got "${fm.type}"`, severity: 'error' });
  }

  checkRequired(fm, RULE_REQUIRED_FIELDS, errors);

  if (fm.source !== undefined && fm.source !== sourceSlug) {
    errors.push({
      field: 'source',
      message: `Frontmatter source "${fm.source}" does not match bundle folder "${sourceSlug}"`,
      severity: 'error',
    });
  }

  // Deprecated rules legitimately carry `severity: null` in the export
  const severityMissing = fm.severity === undefined || fm.severity === null || fm.severity === '';
  if (severityMissing && fm.maturity !== 'deprecated') {
    errors.push({ field: 'severity', message: 'Required for non-deprecated rules', severity: 'error' });
  }

  if (fm.maturity === undefined || fm.maturity === '') {
    warnings.push({ field: 'maturity', message: 'Missing maturity', severity: 'warning' });
  }

  return buildResult(errors, warnings);
}

/**
 * Validates the frontmatter of a source Concept (bundle/sources/<slug>.md).
 *
 * @param fm - Parsed frontmatter object
 * @param fileSlug - Filename-derived slug the frontmatter slug must match
 */
export function validateSourceFrontmatter(fm: Record<string, unknown>, fileSlug: string): ValidationResult {
  const errors: ValidationError[] = [];
  const warnings: ValidationError[] = [];

  if (fm.type !== 'Validation Rule Source') {
    errors.push({
      field: 'type',
      message: `Expected type "Validation Rule Source", got "${fm.type}"`,
      severity: 'error',
    });
  }

  checkRequired(fm, SOURCE_REQUIRED_FIELDS, errors);

  if (fm.slug !== undefined && fm.slug !== fileSlug) {
    errors.push({
      field: 'slug',
      message: `Frontmatter slug "${fm.slug}" does not match filename "${fileSlug}"`,
      severity: 'error',
    });
  }

  return buildResult(errors, warnings);
}
